{{- if (index .Values "backend-py").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-py.fullname" . }}
  labels:
    {{- include "backend-py.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ (index .Values "backend-py").deploymentStrategy }}
  {{- if not (index .Values "backend-py").autoscaling.enabled }}
  replicas: {{ (index .Values "backend-py").replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend-py.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "backend-py.labels" . | nindent 8 }}
    spec:
      {{- if (index .Values "backend-py").podSecurityContext }}
      securityContext:
        {{- toYaml (index .Values "backend-py").podSecurityContext | nindent 12 }}
      {{- end }}
      initContainers:
        - name: {{ include "backend-py.fullname" . }}-init
          image: "{{.Values.global.registry}}/{{.Values.global.repository}}/migrations-py:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" (index .Values "backend-py").imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-py-flyway
          env:
            - name: FLYWAY_BASELINE_ON_MIGRATE
              value: "true"
            - name: FLYWAY_DEFAULT_SCHEMA
              value: "py_api"
            - name: FLYWAY_CONNECT_RETRIES
              value: "10"
            - name: FLYWAY_GROUP
              value: "true"
          resources:
            requests:
              cpu: 20m
              memory: 150Mi
      containers:
        - name: {{ include "backend-py.fullname" . }}
          {{- if (index .Values "backend-py").securityContext }}
          securityContext:
            {{- toYaml (index .Values "backend-py").securityContext | nindent 12 }}
          {{- end }}
          image: "{{.Values.global.registry}}/{{.Values.global.repository}}/backend-py:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" (index .Values "backend-py").imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-py
          env:
            - name: LOG_LEVEL
              value: info
            - name: PYTHONPATH
              value: /application/app/src
          volumeMounts:
            - mountPath: /opt
              name: logger-conf
          ports:
            - name: http
              containerPort: {{ (index .Values "backend-py").service.targetPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          resources: # this is optional
            requests:
              cpu: 20m
              memory: 150Mi
      volumes:
        - name: logger-conf
          configMap:
            name: {{ include "backend-py.fullname" . }}
      {{- with (index .Values "backend-py").nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "backend-py").tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "backend-py.fullname" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"

{{- end }}
