{{- if (index .Values "backend-py").enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-py.fullname" . }}
  labels:
    {{- include "backend-py.labels" . | nindent 4 }}
spec:
  type: {{ (index .Values "backend-py").service.type }}
  ports:
    - port: {{ (index .Values "backend-py").service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend-py.selectorLabels" . | nindent 4 }}
{{- end }}
