{{- if (index .Values "backend-java").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-java.fullname" . }}
  labels:
    {{- include "backend-java.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ (index .Values "backend-java").deploymentStrategy }}
  {{- if not (index .Values "backend-java").autoscaling.enabled }}
  replicas: {{ (index .Values "backend-java").replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "backend-java.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "backend-java.labels" . | nindent 8 }}
    spec:
      {{- if (index .Values "backend-java").podSecurityContext }}
      securityContext:
        {{- toYaml (index .Values "backend-java").podSecurityContext | nindent 12 }}
      {{- end }}
      containers:
        - name: {{ include "backend-java.fullname" . }}
          {{- if (index .Values "backend-java").securityContext }}
          securityContext:
            {{- toYaml (index .Values "backend-java").securityContext | nindent 12 }}
          {{- end }}
          image: "{{.Values.global.registry}}/{{.Values.global.repository}}/backend-java:{{ .Values.global.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ default "Always" (index .Values "backend-java").imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{.Release.Name}}-java
          env:
            - name: QUARKUS_DATASOURCE_JDBC_POOLING_ENABLED
              value: "false" # using pgbouncer
            - name: LOG_LEVEL
              value: info
          ports:
            - name: http
              containerPort: {{ (index .Values "backend-java").service.targetPort }}
              protocol: TCP
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 1
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 30
          livenessProbe:
            successThreshold: 1
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 5
          resources: # this is optional
            requests:
              cpu: 20m
              memory: 150Mi
      {{- with (index .Values "backend-java").nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "backend-java").tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - {{ include "backend-java.fullname" . }}
                  - key: app.kubernetes.io/instance
                    operator: In
                    values:
                      - {{ .Release.Name }}
              topologyKey: "kubernetes.io/hostname"

{{- end }}
