{{- if and (index .Values "backend-java").pdb  (index .Values "backend-java").pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "backend-java.fullname" . }}
  labels:
    {{- include "backend-java.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backend-java.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ (index .Values "backend-java").pdb.minAvailable }}
{{- end }}
