{{- if (index .Values "backend-java").enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "backend-java.labels" . | nindent 4 }}
  name: {{ include "backend-java.fullname" . }}
spec:
  host: {{ include "backend-java.fullname" . }}.{{ .Values.global.domain }}
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "backend-java.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
