{{- if (index .Values "backend-java").enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-java.fullname" . }}
  labels:
    {{- include "backend-java.labels" . | nindent 4 }}
spec:
  type: {{ (index .Values "backend-java").service.type }}
  ports:
    - port: {{ (index .Values "backend-java").service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "backend-java.selectorLabels" . | nindent 4 }}
{{- end }}
